# Generated by Django 5.2.17 on 2026-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
